### ISSUE TITLE
Error: 'grep' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by ChristofLee** [bnlucas/SassBuilder#13]
```
Writing file /C/wamp/www/install/content/theme/RENAME_THIS_THEME/scss/_config.scss with encoding UTF-8 'grep' is not recognized as an internal or external command, operable program or batch file.

error: Sass Error: Hit 'ctrl+`' to see errors.
Exception in thread Thread-19:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File ".\threading.py", line 484, in run
  File ".\SassBuilder.py", line 65, in compile
TypeError: 'NoneType' object is not iterable
```

I have installed Ruby and Sass without issue and can use them to compile via the cmd prompt. But when I use this plugin I keep getting the above error. How can I fix this?

**Comment by ChristofLee** [comment]
I installed grep separately bu I still get:
```
Writing file /C/wamp/www/install/content/theme/RENAME_THIS_THEME/scss/_slider.scss with encoding UTF-8
Exception in thread Thread-12:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File ".\threading.py", line 484, in run
  File ".\SassBuilder.py", line 65, in compile
TypeError: 'NoneType' object is not iterable
```

**Comment by bnlucas** [comment]
I'm taking a look into this. The `grep` command was added in a pull request and never tested properly. The simple fact that Windows users don't have access to `grep` without installing it is something that I'm looking into, going with a pure python route instead if `grep` is not present. There will be more to come!

**Comment by ChristofLee** [comment]
Thanks for getting back to me, not had the issue until installing `sassbuilder` around 13th June 15 (previously, on other machines, it worked fine).

In regards to the error that is being returned, the main `.scss` compiles fine and includes the partials, but when directly saving a partial I get the above error code. I'm a little confused because I have this on several other machines and saving a partial compiles just fine.

**Comment by bnlucas** [comment]
Not sure on the exact cause of the error, but I have pushed the updates to this and have tested it locally, seems to running now.

**Comment by ChristofLee** [comment]
Thanks for the update.

I'm still having issues though along with two other devs. We are running Mac OS X with Python v2.6 and cant get `sassbuilder` to run. We all get the same error: 
```
Writing file /Volumes/fifteen/sites/5363-fifteen/wp-content/themes/5363-fifteen/scss/style.scss with encoding UTF-8
SassBuilder started.
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./SassBuilder.py", line 132, in compile_sass
ValueError: zero length field name in format
```

**Comment by bnlucas** [comment]
It seems the Thread call is causing issues on some systems. This has been updated to remove it completely. I was only able to test this on a Windows 8.2 system with Python 2.7 and 3.4. Hopefully this will get it going for you guys!
